name: Release Binary Assets
on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  BINARY_NAME: ssd-benchmark

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            binName: ${{ env.BINARY_NAME }}
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
            binName: ${{ env.BINARY_NAME }}
          - target: x86_64-apple-darwin
            os: macos-latest
            cross: false
            binName: ${{ env.BINARY_NAME }}
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            cross: false
            binName: ${{ env.BINARY_NAME }}.exe
          - target: x86_64-pc-windows-gnu
            os: windows-latest
            cross: false
            binName: ${{ env.BINARY_NAME }}.exe
    steps:
      - uses: actions/checkout@v4
      - name: setup | rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        if: ${{ matrix.cross == true }}
        with:
          tool: cross
      - name: build with cross
        if: ${{ matrix.cross == true }}
        shell: bash
        run: cross build --locked --release --target ${{ matrix.target }}
      - name: smoke test
        if: ${{ matrix.cross == true }}
        shell: bash
        run: |
          cross run --locked --release --target ${{ matrix.target }} -- --help
      - name: build with cargo
        if: ${{ matrix.cross != true }}
        shell: bash
        run: cargo build --locked --release --target ${{ matrix.target }}
      - name: smoke test with cargo
        if: ${{ matrix.cross != true }}
        shell: bash
        run: |
          cargo run --locked --release --target ${{ matrix.target }} -- --help
      - name: Create Archive
        id: archive
        shell: bash
        env:
          TARGET: ${{ matrix.target }}
          TAG: ${{ github.event.release.tag_name }}
        run: |
          filename="${{ env.BINARY_NAME }}-$TAG-$TARGET.tar.gz"
          tar -czvf "$filename" README.md LICENSE -C "target/$TARGET/release" "${{ matrix.binName }}"
          echo "filename=$filename" >> $GITHUB_OUTPUT
      - name: Upload Archive
        uses: ncipollo/release-action@v1.8.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ${{ steps.archive.outputs.filename }}
          artifactContentType: application/octet-stream
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true

  pkg-deb:
    name: binary package .deb
    env:
      TARGET: x86_64-unknown-linux-musl
      TAG: ${{ github.event.release.tag_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build .deb file
        uses: sassman/rust-deb-builder@v1
      - name: Archive deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BINARY_NAME }}-${{ env.TAG }}-${{ env.TARGET }}.deb
          path: target/${{ env.TARGET }}/debian/${{ env.BINARY_NAME }}*.deb
      - name: upload deb file
        uses: ncipollo/release-action@v1.8.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: target/${{ env.TARGET }}/debian/${{ env.BINARY_NAME }}*.deb
          artifactContentType: application/octet-stream
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
